from __future__ import annotations

from dataclasses import dataclass
from datetime import date


@dataclass(frozen=True)
class StockUniverseItem:
    ticker: str
    company_name: str
    company_name_en: str
    market: str
    sector: str
    industry: str
    listing_date: date
    corp_code: str


STOCK_UNIVERSE = [
    StockUniverseItem(
        ticker="005930",
        company_name="삼성전자",
        company_name_en="Samsung Electronics",
        market="KOSPI",
        sector="반도체",
        industry="전자부품 제조업",
        listing_date=date(1975, 6, 11),
        corp_code="00126380",
    ),
    StockUniverseItem(
        ticker="000660",
        company_name="SK하이닉스",
        company_name_en="SK hynix",
        market="KOSPI",
        sector="반도체",
        industry="메모리 반도체 제조업",
        listing_date=date(1996, 12, 26),
        corp_code="00164779",
    ),
    StockUniverseItem(
        ticker="035420",
        company_name="NAVER",
        company_name_en="NAVER",
        market="KOSPI",
        sector="인터넷",
        industry="포털 및 플랫폼 서비스",
        listing_date=date(2002, 10, 29),
        corp_code="00266961",
    ),
    StockUniverseItem(
        ticker="035720",
        company_name="카카오",
        company_name_en="Kakao",
        market="KOSPI",
        sector="인터넷",
        industry="모바일 플랫폼 서비스",
        listing_date=date(2017, 7, 10),
        corp_code="00258801",
    ),
    StockUniverseItem(
        ticker="051910",
        company_name="LG화학",
        company_name_en="LG Chem",
        market="KOSPI",
        sector="화학",
        industry="기초 화학물질 제조업",
        listing_date=date(2001, 4, 25),
        corp_code="00356361",
    ),
    StockUniverseItem(
        ticker="006400",
        company_name="삼성SDI",
        company_name_en="Samsung SDI",
        market="KOSPI",
        sector="2차전지",
        industry="축전지 제조업",
        listing_date=date(1979, 2, 27),
        corp_code="00126362",
    ),
    StockUniverseItem(
        ticker="068270",
        company_name="셀트리온",
        company_name_en="Celltrion",
        market="KOSPI",
        sector="바이오",
        industry="바이오 의약품 제조업",
        listing_date=date(2018, 2, 9),
        corp_code="00413046",
    ),
    StockUniverseItem(
        ticker="005380",
        company_name="현대차",
        company_name_en="Hyundai Motor",
        market="KOSPI",
        sector="자동차",
        industry="자동차 제조업",
        listing_date=date(1974, 6, 28),
        corp_code="00164742",
    ),
    StockUniverseItem(
        ticker="000270",
        company_name="기아",
        company_name_en="Kia",
        market="KOSPI",
        sector="자동차",
        industry="자동차 제조업",
        listing_date=date(1973, 7, 21),
        corp_code="00106641",
    ),
    StockUniverseItem(
        ticker="012330",
        company_name="현대모비스",
        company_name_en="Hyundai Mobis",
        market="KOSPI",
        sector="자동차부품",
        industry="자동차 부품 제조업",
        listing_date=date(1989, 9, 5),
        corp_code="00164788",
    ),
    StockUniverseItem(
        ticker="373220",
        company_name="LG에너지솔루션",
        company_name_en="LG Energy Solution",
        market="KOSPI",
        sector="2차전지",
        industry="축전지 제조업",
        listing_date=date(2022, 1, 27),
        corp_code="01515323",
    ),
    StockUniverseItem(
        ticker="207940",
        company_name="삼성바이오로직스",
        company_name_en="Samsung Biologics",
        market="KOSPI",
        sector="바이오",
        industry="바이오 의약품 위탁생산",
        listing_date=date(2016, 11, 10),
        corp_code="00877059",
    ),
    StockUniverseItem(
        ticker="105560",
        company_name="KB금융",
        company_name_en="KB Financial Group",
        market="KOSPI",
        sector="금융",
        industry="금융지주회사",
        listing_date=date(2008, 10, 10),
        corp_code="00688996",
    ),
    StockUniverseItem(
        ticker="055550",
        company_name="신한지주",
        company_name_en="Shinhan Financial Group",
        market="KOSPI",
        sector="금융",
        industry="금융지주회사",
        listing_date=date(2001, 9, 10),
        corp_code="00382199",
    ),
    StockUniverseItem(
        ticker="086790",
        company_name="하나금융지주",
        company_name_en="Hana Financial Group",
        market="KOSPI",
        sector="금융",
        industry="금융지주회사",
        listing_date=date(2005, 12, 12),
        corp_code="00547583",
    ),
    StockUniverseItem(
        ticker="034730",
        company_name="SK",
        company_name_en="SK Inc.",
        market="KOSPI",
        sector="지주",
        industry="지주회사",
        listing_date=date(2009, 11, 11),
        corp_code="00181712",
    ),
    StockUniverseItem(
        ticker="096770",
        company_name="SK이노베이션",
        company_name_en="SK Innovation",
        market="KOSPI",
        sector="에너지",
        industry="석유 정제품 제조업",
        listing_date=date(2007, 7, 25),
        corp_code="00631518",
    ),
    StockUniverseItem(
        ticker="003670",
        company_name="포스코퓨처엠",
        company_name_en="POSCO Future M",
        market="KOSPI",
        sector="2차전지",
        industry="이차전지 소재 제조업",
        listing_date=date(1989, 9, 5),
        corp_code="00155276",
    ),
    StockUniverseItem(
        ticker="005490",
        company_name="POSCO홀딩스",
        company_name_en="POSCO Holdings",
        market="KOSPI",
        sector="철강",
        industry="지주 및 철강",
        listing_date=date(1988, 6, 10),
        corp_code="00155319",
    ),
    StockUniverseItem(
        ticker="066570",
        company_name="LG전자",
        company_name_en="LG Electronics",
        market="KOSPI",
        sector="전자",
        industry="가전 및 전자제품 제조업",
        listing_date=date(2002, 4, 22),
        corp_code="00401731",
    ),
    StockUniverseItem(
        ticker="032830",
        company_name="삼성생명",
        company_name_en="Samsung Life Insurance",
        market="KOSPI",
        sector="보험",
        industry="생명보험업",
        listing_date=date(2010, 5, 12),
        corp_code="00126256",
    ),
    StockUniverseItem(
        ticker="000810",
        company_name="삼성화재",
        company_name_en="Samsung Fire & Marine Insurance",
        market="KOSPI",
        sector="보험",
        industry="손해보험업",
        listing_date=date(1975, 6, 30),
        corp_code="00126434",
    ),
    StockUniverseItem(
        ticker="090430",
        company_name="아모레퍼시픽",
        company_name_en="Amorepacific",
        market="KOSPI",
        sector="화장품",
        industry="화장품 제조업",
        listing_date=date(2006, 6, 29),
        corp_code="00583424",
    ),
    StockUniverseItem(
        ticker="018260",
        company_name="삼성에스디에스",
        company_name_en="Samsung SDS",
        market="KOSPI",
        sector="IT서비스",
        industry="시스템 통합 및 IT 서비스",
        listing_date=date(2014, 11, 14),
        corp_code="00126186",
    ),
    StockUniverseItem(
        ticker="009150",
        company_name="삼성전기",
        company_name_en="Samsung Electro-Mechanics",
        market="KOSPI",
        sector="전자부품",
        industry="전자부품 제조업",
        listing_date=date(1979, 2, 27),
        corp_code="00126344",
    ),
    StockUniverseItem(
        ticker="010950",
        company_name="S-Oil",
        company_name_en="S-Oil",
        market="KOSPI",
        sector="에너지",
        industry="석유 정제품 제조업",
        listing_date=date(1987, 5, 27),
        corp_code="00138262",
    ),
    StockUniverseItem(
        ticker="011200",
        company_name="HMM",
        company_name_en="HMM",
        market="KOSPI",
        sector="운송",
        industry="해상 운송업",
        listing_date=date(1995, 10, 5),
        corp_code="00164645",
    ),
    StockUniverseItem(
        ticker="028260",
        company_name="삼성물산",
        company_name_en="Samsung C&T",
        market="KOSPI",
        sector="상사/건설",
        industry="종합상사 및 건설",
        listing_date=date(2014, 12, 18),
        corp_code="00126371",
    ),
    StockUniverseItem(
        ticker="024110",
        company_name="기업은행",
        company_name_en="Industrial Bank of Korea",
        market="KOSPI",
        sector="금융",
        industry="은행업",
        listing_date=date(2003, 12, 24),
        corp_code="00149646",
    ),
    StockUniverseItem(
        ticker="316140",
        company_name="우리금융지주",
        company_name_en="Woori Financial Group",
        market="KOSPI",
        sector="금융",
        industry="금융지주회사",
        listing_date=date(2019, 2, 13),
        corp_code="01350869",
    ),
]

MAJOR_STOCK_TICKERS = [
    item.ticker
    for item in STOCK_UNIVERSE[:20]
]
